package org.hibernate.compositekeymapping;

import org.hibernate.common.AbstractTest;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.hibernate.relations.compositekeymapping.CompositeKeyWithAutoGenerationColumn.OrderId;
import static org.hibernate.relations.compositekeymapping.CompositeKeyWithAutoGenerationColumn.Order;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class CompositeKeyWithAutoGenerationColumnTest extends AbstractTest
{
    @Test
    public void testCompositeKeyWhenOneColumnAutoGenerated()
    {
        Order savedOrder = transactionManager.executeTransaction(entityManager ->
        {
            Order order = new Order();
            order.setCustomerId(1L);
            order.setOrderDate(LocalDate.now());
            order.setTotalAmount(12d);

            entityManager.persist(order);
            return order;
        }, entities);

        transactionManager.executeTransaction(entityManager ->
        {
            OrderId orderId = new OrderId();
            orderId.setOrderNumber(savedOrder.getOrderNumber());
            orderId.setCustomerId(1L);
            Order order = entityManager.find(Order.class, orderId);
            assertNotNull(order);
            assertEquals(12d, order.getTotalAmount());
        }, entities);
    }

    @Override
    public Class<?>[] getEntities()
    {
        return new Class[] { Order.class };
    }
}
